---
# tasks file for common
# This Playbook runs all the common plays in the deployment
- name: install 58mongodb
  hosts: backup_host
  gather_facts: True
  tasks:
    - name: Create the repository for 58mongodb 
      copy: src=../template/58db.repo.j2 dest=/etc/yum.repos.d/58db.repo
    - name: Install the zip file
      copy: src=../package/pigz dest=/usr/bin/pigz
    - name: Install mysql client
      copy: src=../package/mysql dest=/usr/bin/mysql

    - name: Install the mongodb package
      yum: name=58mongodb32   state=latest
      when: (ansible_distribution_version == "6.5")
    - name: Install the mongodb rpm package 
      script: ../script/backup_install_package.sh
      when: (ansible_distribution_version != "6.5")
